#requires -Version 5.1
# Generated by Build-IntuneWin.ps1. Upload the generated Output/Detect-OfficeWiFi.ps1.
$ErrorActionPreference = 'Stop'
if ([Environment]::Is64BitOperatingSystem -and -not [Environment]::Is64BitProcess) {
    & "$env:WINDIR\Sysnative\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $PSCommandPath
    exit $LASTEXITCODE
}
try {
    $root = Join-Path ([Environment]::GetFolderPath('ProgramFiles')) 'OfficeWiFiEnforcer'
    $expectedFiles = @'
__EXPECTED_HASHES_JSON__
'@ | ConvertFrom-Json
    $info = Get-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\OfficeWiFiEnforcer' -ErrorAction Stop
    if ($info.PackageVersion -ne '__PACKAGE_VERSION__' -or $info.PolicyVersion -ne '__POLICY_VERSION__' -or
        $info.ConfigHash -ne '__CONFIG_HASH__' -or $info.InstallRoot -ine $root -or $info.TaskName -cne 'OfficeWiFi-Enforcer') { exit 1 }
    if ((Get-Item -LiteralPath $root -Force).Attributes -band [IO.FileAttributes]::ReparsePoint) { exit 1 }
    foreach ($p in $expectedFiles.PSObject.Properties) {
        $path = Join-Path $root $p.Name
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { exit 1 }
        if ((Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash -ne $p.Value) { exit 1 }
    }
    $scheduler = New-Object -ComObject 'Schedule.Service'
    $scheduler.Connect()
    $task = $scheduler.GetFolder('\').GetTask('OfficeWiFi-Enforcer')
    $d = $task.Definition
    if (-not $task.Enabled -or $d.Principal.UserId -notin @('SYSTEM','NT AUTHORITY\SYSTEM','S-1-5-18') -or
        $d.Principal.LogonType -ne 5 -or $d.Principal.RunLevel -ne 1 -or $d.Actions.Count -ne 1) { exit 1 }
    $a = $d.Actions.Item(1)
    $expectedHost = Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe'
    $expectedArguments = '-NoLogo -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File "' + (Join-Path $root 'Enforce-OfficeWiFi.ps1') + '"'
    if ($a.Path -ine $expectedHost -or $a.Arguments -cne $expectedArguments -or $a.WorkingDirectory -ine $root) { exit 1 }
    if ($d.Settings.MultipleInstances -ne 2 -or $d.Settings.DisallowStartIfOnBatteries -or
        $d.Settings.StopIfGoingOnBatteries -or $d.Settings.RunOnlyIfNetworkAvailable -or -not $d.Settings.StartWhenAvailable) { exit 1 }
    $boot = $false; $logon = $false; $repeat = $false
    for ($i = 1; $i -le $d.Triggers.Count; $i++) {
        $trigger = $d.Triggers.Item($i)
        if (-not $trigger.Enabled) { continue }
        if ($trigger.Type -eq 8) { $boot = $true }
        if ($trigger.Type -eq 9) { $logon = $true }
        if ($trigger.Type -eq 1 -and [Xml.XmlConvert]::ToTimeSpan($trigger.Repetition.Interval).TotalMinutes -eq ([int]'__INTERVAL__') -and
            -not $trigger.Repetition.Duration -and -not $trigger.EndBoundary) { $repeat = $true }
    }
    if (-not ($boot -and $logon -and $repeat)) { exit 1 }
    Write-Output 'OfficeWiFi-Enforcer __PACKAGE_VERSION__; policy __POLICY_VERSION__ installed.'
    exit 0
} catch { exit 1 }
